In [1]:
import pandas as pd
import logging
import os
from pipeline import extract, transform, load, etl_pipeline
logging.basicConfig(format = '%(levelname)s:%(message)s', level = logging.DEBUG)

In [2]:
wine_data = extract('winemag-data_first150k.csv')
wine_data

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...,...
150925,150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [3]:
df = transform(wine_data)
df

/mnt/c/Users/user/Documents/Repositories/ETL-pipeline-project-practice/pipeline.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data.fillna({'price': round(raw_data['price'].mean(), 2),

,country,description,points,price,region_1,region_2
0,US,This tremendous 100% varietal wine hails from ...,96,235.0,Napa Valley,Napa
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",96,110.0,Toro,missing
2,US,Mac Watson honors the memory of a wine once ma...,96,90.0,Knights Valley,Sonoma
3,US,"This spent 20 months in 30% new French oak, an...",96,65.0,Willamette Valley,Willamette Valley
4,France,"This is the top wine from La Bégude, named aft...",95,66.0,Bandol,missing
...,...,...,...,...,...,...
95,France,"This is a smooth, soft wine that is full of bl...",86,14.0,Cahors,missing
96,US,This is an easygoing wine that's neither too o...,86,18.0,California,California Other
97,US,"Blended with small amounts of Merlot, Cabernet...",86,36.0,Sonoma Valley,Sonoma
98,France,"Closer to Bordeaux than is Cahors, this is Mal...",86,15.0,Buzet,missing
99,France,This is a blend of 60% Ugni Blanc and 40% Colo...,86,10.0,Côtes de Gascogne,missing

In [4]:
final_data = load(df, 'test_run.csv')
final_data

In [5]:
file_exists = os.path.exists('test_run.csv')
file_exists

True

In [6]:
processed_data = etl_pipeline('winemag-data_first150k.csv', 'test_run.csv')
processed_data

/mnt/c/Users/user/Documents/Repositories/ETL-pipeline-project-practice/pipeline.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data.fillna({'price': round(raw_data['price'].mean(), 2),

{'ETL completed, Data saved to test_run.csv'}

In [7]:
try:
    raw_data = extract('winemag-data-130k-v2.csv')
    processed_data = transform(raw_data)
    logging.info("Successfully set the index to country")
    load(processed_data, 'transformed_130k_wine.csv')
    logging.info("Successfully extracted, transformed and loaded the wine 130k data")
except Exception as e:
    logging.error(f"pipeline failed with error : {e}")

/mnt/c/Users/user/Documents/Repositories/ETL-pipeline-project-practice/pipeline.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data.fillna({'price': round(raw_data['price'].mean(), 2),
INFO:Successfully set the index to country
INFO:Successfully extracted, transformed and loaded the wine 130k data

In [8]:
df = pd.read_csv('transformed_130k_wine.csv')
df.head()

,country,description,points,price,region_1,region_2
0,Italy,"Aromas include tropical fruit, broom, brimston...",87,35.36,Etna,missing
1,Portugal,"This is ripe and fruity, a wine that is smooth...",87,15.00,missing,missing
2,US,"Tart and snappy, the flavors of lime flesh and...",87,14.00,Willamette Valley,Willamette Valley
3,US,"Pineapple rind, lemon pith and orange blossom ...",87,13.00,Lake Michigan Shore,missing
4,US,"Much like the regular bottling from 2012, this...",87,65.00,Willamette Valley,Willamette Valley

In [9]:
wine2_data = etl_pipeline('winemag-data-130k-v2.csv', 'wine2_processed.csv')
wine2_data

/mnt/c/Users/user/Documents/Repositories/ETL-pipeline-project-practice/pipeline.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data.fillna({'price': round(raw_data['price'].mean(), 2),

{'ETL completed, Data saved to wine2_processed.csv'}

In [13]:
pip install "apache-airflow[celery]==3.0.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.0.3/constraints-3.9.txt"

ERROR: Ignored the following yanked versions: 1.10.11, 1.10.13
ERROR: Ignored the following versions that require a different python version: 2.10.0 Requires-Python <3.13,~=3.8; 2.10.0b1 Requires-Python <3.13,~=3.8; 2.10.0b2 Requires-Python <3.13,~=3.8; 2.10.0rc1 Requires-Python <3.13,~=3.8; 2.10.1 Requires-Python <3.13,~=3.8; 2.10.1rc1 Requires-Python <3.13,~=3.8; 2.10.2 Requires-Python <3.13,~=3.8; 2.10.2rc1 Requires-Python <3.13,~=3.8; 2.10.3 Requires-Python <3.13,~=3.8; 2.10.3rc1 Requires-Python <3.13,~=3.8; 2.10.3rc2 Requires-Python <3.13,~=3.8; 2.10.4 Requires-Python <3.13,>=3.8.1; 2.10.4rc1 Requires-Python <3.13,>=3.8.1; 2.10.5 Requires-Python <3.13,>=3.8.1; 2.10.5rc1 Requires-Python <3.13,>=3.8.1; 2.11.0 Requires-Python <3.13,>=3.9; 2.11.0rc1 Requires-Python <3.13,>=3.9; 2.7.3 Requires-Python <3.12,~=3.8; 2.7.3rc1 Requires-Python <3.12,~=3.8; 2.8.0 Requires-Python <3.12,~=3.8; 2.8.0b1 Requires-Python <3.12,~=3.8; 2.8.0rc1 Requires-Python <3.12,~=3.8; 2.8.0rc2 Requires-Python <3.12,~=3.8; 2.8.0rc3 Requires-Python <3.12,~=3.8; 2.8.0rc4 Requires-Python <3.12,~=3.8; 2.8.1 Requires-Python <3.12,~=3.8; 2.8.1rc1 Requires-Python <3.12,~=3.8; 2.8.2 Requires-Python <3.12,~=3.8; 2.8.2rc1 Requires-Python <3.12,~=3.8; 2.8.2rc2 Requires-Python <3.12,~=3.8; 2.8.2rc3 Requires-Python <3.12,~=3.8; 2.8.3 Requires-Python <3.12,~=3.8; 2.8.3rc1 Requires-Python <3.12,~=3.8; 2.8.4 Requires-Python <3.12,~=3.8; 2.8.4rc1 Requires-Python <3.12,~=3.8; 2.9.0 Requires-Python <3.13,~=3.8; 2.9.0b1 Requires-Python <3.13,~=3.8; 2.9.0b2 Requires-Python <3.13,~=3.8; 2.9.0rc1 Requires-Python <3.13,~=3.8; 2.9.0rc2 Requires-Python <3.13,~=3.8; 2.9.0rc3 Requires-Python <3.13,~=3.8; 2.9.1 Requires-Python <3.13,~=3.8; 2.9.1rc1 Requires-Python <3.13,~=3.8; 2.9.1rc2 Requires-Python <3.13,~=3.8; 2.9.2 Requires-Python <3.13,~=3.8; 2.9.2rc1 Requires-Python <3.13,~=3.8; 2.9.3 Requires-Python <3.13,~=3.8; 2.9.3rc1 Requires-Python <3.13,~=3.8; 3.0.0 Requires-Python <3.13,~=3.9; 3.0.0b4 Requires-Python <3.13,~=3.9; 3.0.0rc1 Requires-Python <3.13,~=3.9; 3.0.0rc1.post1 Requires-Python <3.13,~=3.9; 3.0.0rc1.post2 Requires-Python <3.13,~=3.9; 3.0.0rc1.post3 Requires-Python <3.13,~=3.9; 3.0.0rc1.post4 Requires-Python <3.13,~=3.9; 3.0.0rc2 Requires-Python <3.13,~=3.9; 3.0.0rc3 Requires-Python <3.13,~=3.9; 3.0.0rc4 Requires-Python <3.13,~=3.9; 3.0.1 Requires-Python <3.13,~=3.9; 3.0.1rc1 Requires-Python <3.13,~=3.9; 3.0.2 Requires-Python <3.13,~=3.9; 3.0.2rc1 Requires-Python <3.13,~=3.9; 3.0.2rc2 Requires-Python <3.13,~=3.9; 3.0.3 Requires-Python <3.13,~=3.9; 3.0.3rc1 Requires-Python <3.13,~=3.9; 3.0.3rc2 Requires-Python <3.13,~=3.9; 3.0.3rc3 Requires-Python <3.13,~=3.9; 3.0.3rc4 Requires-Python <3.13,~=3.9; 3.0.3rc5 Requires-Python <3.13,~=3.9; 3.0.3rc6 Requires-Python <3.13,~=3.9
ERROR: Could not find a version that satisfies the requirement apache-airflow==3.0.3 (from versions: 1.8.1, 1.8.2rc1, 1.8.2, 1.9.0, 1.10.0, 1.10.1b1, 1.10.1rc2, 1.10.1, 1.10.2b2, 1.10.2rc1, 1.10.2rc2, 1.10.2rc3, 1.10.2, 1.10.3b1, 1.10.3b2, 1.10.3rc1, 1.10.3rc2, 1.10.3, 1.10.4b2, 1.10.4rc1, 1.10.4rc2, 1.10.4rc3, 1.10.4rc4, 1.10.4rc5, 1.10.4, 1.10.5rc1, 1.10.5, 1.10.6rc1, 1.10.6rc2, 1.10.6, 1.10.7rc1, 1.10.7rc2, 1.10.7rc3, 1.10.7, 1.10.8rc1, 1.10.8, 1.10.9rc1, 1.10.9, 1.10.10rc1, 1.10.10rc2, 1.10.10rc3, 1.10.10rc4, 1.10.10rc5, 1.10.10, 1.10.11rc1, 1.10.11rc2, 1.10.12rc1, 1.10.12rc2, 1.10.12rc3, 1.10.12rc4, 1.10.12, 1.10.13rc1, 1.10.14rc1, 1.10.14rc2, 1.10.14rc3, 1.10.14rc4, 1.10.14, 1.10.15rc1, 1.10.15, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3, 2.0.0, 2.0.1rc1, 2.0.1rc2, 2.0.1, 2.0.2rc1, 2.0.2, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1rc1, 2.1.1, 2.1.2rc1, 2.1.2, 2.1.3rc1, 2.1.3, 2.1.4rc1, 2.1.4rc2, 2.1.4, 2.2.0b1, 2.2.0b2, 2.2.0rc1, 2.2.0, 2.2.1rc1, 2.2.1rc2, 2.2.1, 2.2.2rc1, 2.2.2rc2, 2.2.2, 2.2.3rc1, 2.2.3rc2, 2.2.3, 2.2.4rc1, 2.2.4, 2.2.5rc1, 2.2.5rc2, 2.2.5rc3, 2.2.5, 2.3.0b1, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1rc1, 2.3.1, 2.3.2rc1, 2.3.2rc2, 2.3.2, 2.3.3rc1, 2.3.3rc2, 2.3.3rc3, 2.3.3, 2.3.4rc1, 2.3.4, 2.4.0b1, 2.4.0rc1, 2.4.0, 2.4.1rc1, 2.4.1, 2.4.2rc1, 2.4.2, 2.4.3rc1, 2.4.3, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1rc1, 2.5.1rc2, 2.5.1, 2.5.2rc1, 2.5.2rc2, 2.5.2, 2.5.3rc1, 2.5.3rc2, 2.5.3, 2.6.0b1, 2.6.0rc1, 2.6.0rc2, 2.6.0rc3, 2.6.0rc4, 2.6.0rc5, 2.6.0, 2.6.1rc1, 2.6.1rc2, 2.6.1rc3, 2.6.1, 2.6.2rc1, 2.6.2rc2, 2.6.2, 2.6.3rc1, 2.6.3, 2.7.0b1, 2.7.0rc1, 2.7.0rc2, 2.7.0, 2.7.1rc1, 2.7.1rc2, 2.7.1, 2.7.2rc1, 2.7.2)
ERROR: No matching distribution found for apache-airflow==3.0.3
Note: you may need to restart the kernel to use updated packages.

In [15]:
!python3 -m venv airflow-env

In [16]:
!source airflow-env/bin/activate

In [18]:
!pip install apache-airflow

Collecting apache-airflow
  Using cached apache_airflow-2.7.2-py3-none-any.whl.metadata (102 kB)
Collecting alembic<2.0,>=1.6.3 (from apache-airflow)
  Using cached alembic-1.16.4-py3-none-any.whl.metadata (7.3 kB)
Collecting argcomplete>=1.10 (from apache-airflow)
  Using cached argcomplete-3.6.2-py3-none-any.whl.metadata (16 kB)
Collecting asgiref (from apache-airflow)
  Using cached asgiref-3.9.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: attrs>=22.1.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (24.3.0)
Requirement already satisfied: blinker in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (1.9.0)
Collecting cattrs>=22.1.0 (from apache-airflow)
  Using cached cattrs-25.1.1-py3-none-any.whl.metadata (8.4 kB)
Collecting colorlog<5.0,>=4.0.2 (from apache-airflow)
  Using cached colorlog-4.8.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting configupdater>=3.1.1 (from apache-airflow)
  Using cached ConfigUpdater-3.2-py2.py3-none-any.whl.metadata (10 kB)
Collecting connexion>=2.10.0 (from connexion[flask]>=2.10.0->apache-airflow)
  Using cached connexion-3.2.0-py3-none-any.whl.metadata (12 kB)
Collecting cron-descriptor>=1.2.24 (from apache-airflow)
  Using cached cron_descriptor-1.4.5-py3-none-any.whl.metadata (5.7 kB)
Collecting croniter>=0.3.17 (from apache-airflow)
  Using cached croniter-6.0.0-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: cryptography>=0.9.3 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (44.0.1)
Requirement already satisfied: deprecated>=1.2.13 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (1.2.13)
Requirement already satisfied: dill>=0.2.2 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (0.3.8)
Collecting flask<2.3,>=2.2 (from apache-airflow)
  Using cached Flask-2.2.5-py3-none-any.whl.metadata (3.9 kB)
Collecting flask-appbuilder==4.3.6 (from apache-airflow)
  Using cached Flask_AppBuilder-4.3.6-py3-none-any.whl.metadata (8.8 kB)
Collecting flask-caching>=1.5.0 (from apache-airflow)
  Using cached Flask_Caching-2.3.1-py3-none-any.whl.metadata (2.2 kB)
Collecting flask-login>=0.6.2 (from apache-airflow)
  Using cached Flask_Login-0.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting flask-session>=0.4.0 (from apache-airflow)
  Using cached flask_session-0.8.0-py3-none-any.whl.metadata (5.2 kB)
Collecting flask-wtf>=0.15 (from apache-airflow)
  Using cached flask_wtf-1.2.2-py3-none-any.whl.metadata (3.4 kB)
Collecting google-re2>=1.0 (from apache-airflow)
  Using cached google_re2-1.1.20240702.tar.gz (11 kB)
  Preparing metadata (setup.py) ... one
Collecting graphviz>=0.12 (from apache-airflow)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Collecting gunicorn>=20.1.0 (from apache-airflow)
  Using cached gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: httpx in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (0.28.1)
Requirement already satisfied: itsdangerous>=2.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (2.2.0)
Requirement already satisfied: jinja2>=3.0.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (3.1.6)
Requirement already satisfied: jsonschema>=4.18.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (4.23.0)
Collecting lazy-object-proxy (from apache-airflow)
  Using cached lazy_object_proxy-1.11.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: linkify-it-py>=2.0.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (2.0.0)
Collecting lockfile>=0.12.2 (from apache-airflow)
  Using cached lockfile-0.12.2-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: markdown>=3.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (3.8)
Requirement already satisfied: markdown-it-py>=2.1.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (2.2.0)
Requirement already satisfied: markupsafe>=1.1.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (3.0.2)
Collecting marshmallow-oneofschema>=2.0.1 (from apache-airflow)
  Using cached marshmallow_oneofschema-3.2.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: mdit-py-plugins>=0.3.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (0.3.0)
Collecting opentelemetry-api>=1.15.0 (from apache-airflow)
  Using cached opentelemetry_api-1.35.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-otlp (from apache-airflow)
  Using cached opentelemetry_exporter_otlp-1.35.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: packaging>=14.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (24.2)
Requirement already satisfied: pathspec>=0.9.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (0.10.3)
Collecting pendulum>=2.0 (from apache-airflow)
  Using cached pendulum-3.1.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: pluggy>=1.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (1.5.0)
Requirement already satisfied: psutil>=4.2.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (5.9.0)
Requirement already satisfied: pydantic>=1.10.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (2.10.3)
Requirement already satisfied: pygments>=2.0.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (2.19.1)
Requirement already satisfied: pyjwt>=2.0.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (2.10.1)
Collecting python-daemon>=3.0.0 (from apache-airflow)
  Using cached python_daemon-3.1.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: python-dateutil>=2.3 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (2.9.0.post0)
Collecting python-nvd3>=0.15.0 (from apache-airflow)
  Using cached python_nvd3-0.16.0-py3-none-any.whl
Requirement already satisfied: python-slugify>=5.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (5.0.2)
Requirement already satisfied: rfc3339-validator>=0.1.4 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (0.1.4)
Requirement already satisfied: rich>=12.4.4 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (13.9.4)
Collecting rich-argparse>=1.0.0 (from apache-airflow)
  Using cached rich_argparse-1.7.1-py3-none-any.whl.metadata (14 kB)
Collecting setproctitle>=1.1.8 (from apache-airflow)
  Using cached setproctitle-1.3.6-cp313-cp313-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting sqlalchemy<2.0,>=1.4.28 (from apache-airflow)
  Using cached SQLAlchemy-1.4.54-cp313-cp313-linux_x86_64.whl
Collecting sqlalchemy-jsonfield>=1.0 (from apache-airflow)
  Using cached SQLAlchemy_JSONField-1.0.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: tabulate>=0.7.5 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (0.9.0)
Requirement already satisfied: tenacity!=8.2.0,>=6.2.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (9.0.0)
Collecting termcolor>=1.1.0 (from apache-airflow)
  Using cached termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (4.12.2)
Collecting unicodecsv>=0.14.1 (from apache-airflow)
  Using cached unicodecsv-0.14.1-py3-none-any.whl
Requirement already satisfied: werkzeug>=2.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow) (3.1.3)
Collecting apache-airflow-providers-common-sql (from apache-airflow)
  Using cached apache_airflow_providers_common_sql-1.27.3-py3-none-any.whl.metadata (5.4 kB)
Collecting apache-airflow-providers-ftp (from apache-airflow)
  Using cached apache_airflow_providers_ftp-3.13.1-py3-none-any.whl.metadata (5.1 kB)
Collecting apache-airflow-providers-http (from apache-airflow)
  Using cached apache_airflow_providers_http-5.3.2-py3-none-any.whl.metadata (4.1 kB)
Collecting apache-airflow-providers-imap (from apache-airflow)
  Using cached apache_airflow_providers_imap-3.9.1-py3-none-any.whl.metadata (3.7 kB)
Collecting apache-airflow-providers-sqlite (from apache-airflow)
  Using cached apache_airflow_providers_sqlite-4.1.1-py3-none-any.whl.metadata (5.0 kB)
Collecting apispec<7,>=6.0.0 (from apispec[yaml]<7,>=6.0.0->flask-appbuilder==4.3.6->apache-airflow)
  Using cached apispec-6.8.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: colorama<1,>=0.3.9 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from flask-appbuilder==4.3.6->apache-airflow) (0.4.6)
Requirement already satisfied: click<9,>=8 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from flask-appbuilder==4.3.6->apache-airflow) (8.1.8)
Collecting email-validator<2,>=1.0.5 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached email_validator-1.3.1-py2.py3-none-any.whl.metadata (23 kB)
Collecting Flask-Babel<3,>=1 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached Flask_Babel-2.0.0-py3-none-any.whl.metadata (2.1 kB)
Collecting Flask-Limiter<4,>3 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached flask_limiter-3.12-py3-none-any.whl.metadata (6.3 kB)
Collecting Flask-SQLAlchemy<3,>=2.4 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting Flask-JWT-Extended<5.0.0,>=4.0.0 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached Flask_JWT_Extended-4.7.1-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting marshmallow<4,>=3.18.0 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting marshmallow-sqlalchemy<0.27.0,>=0.22.0 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached marshmallow_sqlalchemy-0.26.1-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting prison<1.0.0,>=0.2.1 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached prison-0.2.1-py2.py3-none-any.whl.metadata (973 bytes)
Collecting sqlalchemy-utils<1,>=0.32.21 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached SQLAlchemy_Utils-0.41.2-py3-none-any.whl.metadata (4.2 kB)
Collecting WTForms<4 (from flask-appbuilder==4.3.6->apache-airflow)
  Using cached wtforms-3.2.1-py3-none-any.whl.metadata (5.3 kB)
Collecting Mako (from alembic<2.0,>=1.6.3->apache-airflow)
  Using cached mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: PyYAML>=3.10 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apispec[yaml]<7,>=6.0.0->flask-appbuilder==4.3.6->apache-airflow) (6.0.2)
Collecting dnspython>=1.15.0 (from email-validator<2,>=1.0.5->flask-appbuilder==4.3.6->apache-airflow)
  Using cached dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: idna>=2.0.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from email-validator<2,>=1.0.5->flask-appbuilder==4.3.6->apache-airflow) (3.7)
Requirement already satisfied: pytz in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from Flask-Babel<3,>=1->flask-appbuilder==4.3.6->apache-airflow) (2024.1)
Requirement already satisfied: Babel>=2.3 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from Flask-Babel<3,>=1->flask-appbuilder==4.3.6->apache-airflow) (2.16.0)
Collecting limits>=3.13 (from Flask-Limiter<4,>3->flask-appbuilder==4.3.6->apache-airflow)
  Using cached limits-5.4.0-py3-none-any.whl.metadata (10 kB)
Collecting ordered-set<5,>4 (from Flask-Limiter<4,>3->flask-appbuilder==4.3.6->apache-airflow)
  Using cached ordered_set-4.1.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from jsonschema>=4.18.0->apache-airflow) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from jsonschema>=4.18.0->apache-airflow) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from jsonschema>=4.18.0->apache-airflow) (0.22.3)
Requirement already satisfied: six in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from prison<1.0.0,>=0.2.1->flask-appbuilder==4.3.6->apache-airflow) (1.17.0)
Requirement already satisfied: greenlet!=0.4.17 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from sqlalchemy<2.0,>=1.4.28->apache-airflow) (3.1.1)
Requirement already satisfied: inflection>=0.3.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from connexion>=2.10.0->connexion[flask]>=2.10.0->apache-airflow) (0.5.1)
Collecting python-multipart>=0.0.15 (from connexion>=2.10.0->connexion[flask]>=2.10.0->apache-airflow)
  Using cached python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: requests>=2.27 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from connexion>=2.10.0->connexion[flask]>=2.10.0->apache-airflow) (2.32.3)
Collecting starlette>=0.35 (from connexion>=2.10.0->connexion[flask]>=2.10.0->apache-airflow)
  Using cached starlette-0.47.2-py3-none-any.whl.metadata (6.2 kB)
Collecting a2wsgi>=1.7 (from connexion[flask]>=2.10.0->apache-airflow)
  Using cached a2wsgi-1.10.10-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: cffi>=1.12 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from cryptography>=0.9.3->apache-airflow) (1.17.1)
Requirement already satisfied: pycparser in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=0.9.3->apache-airflow) (2.21)
Requirement already satisfied: wrapt<2,>=1.10 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from deprecated>=1.2.13->apache-airflow) (1.17.0)
Collecting cachelib>=0.9.0 (from flask-caching>=1.5.0->apache-airflow)
  Using cached cachelib-0.13.0-py3-none-any.whl.metadata (2.0 kB)
Collecting msgspec>=0.18.6 (from flask-session>=0.4.0->apache-airflow)
  Using cached msgspec-0.19.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
Requirement already satisfied: anyio in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from httpx->apache-airflow) (4.7.0)
Requirement already satisfied: certifi in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from httpx->apache-airflow) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from httpx->apache-airflow) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx->apache-airflow) (0.16.0)
Requirement already satisfied: uc-micro-py in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from linkify-it-py>=2.0.0->apache-airflow) (1.0.1)
Requirement already satisfied: mdurl~=0.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from markdown-it-py>=2.1.0->apache-airflow) (0.1.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from opentelemetry-api>=1.15.0->apache-airflow) (8.5.0)
Requirement already satisfied: zipp>=3.20 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.15.0->apache-airflow) (3.21.0)
Requirement already satisfied: tzdata>=2020.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from pendulum>=2.0->apache-airflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from pydantic>=1.10.0->apache-airflow) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from pydantic>=1.10.0->apache-airflow) (2.27.1)
Requirement already satisfied: text-unidecode>=1.3 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from python-slugify>=5.0->apache-airflow) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from requests>=2.27->connexion>=2.10.0->connexion[flask]>=2.10.0->apache-airflow) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from requests>=2.27->connexion>=2.10.0->connexion[flask]>=2.10.0->apache-airflow) (2.3.0)
Requirement already satisfied: sniffio>=1.1 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from anyio->httpx->apache-airflow) (1.3.0)
INFO: pip is looking at multiple versions of apache-airflow-providers-common-sql to determine which version is compatible with other requirements. This could take a while.
Collecting apache-airflow-providers-common-sql (from apache-airflow)
  Using cached apache_airflow_providers_common_sql-1.27.2-py3-none-any.whl.metadata (5.3 kB)
  Using cached apache_airflow_providers_common_sql-1.27.1-py3-none-any.whl.metadata (5.3 kB)
  Using cached apache_airflow_providers_common_sql-1.27.0-py3-none-any.whl.metadata (5.3 kB)
  Using cached apache_airflow_providers_common_sql-1.26.0-py3-none-any.whl.metadata (5.3 kB)
  Using cached apache_airflow_providers_common_sql-1.25.0-py3-none-any.whl.metadata (5.3 kB)
  Using cached apache_airflow_providers_common_sql-1.24.1-py3-none-any.whl.metadata (5.3 kB)
  Using cached apache_airflow_providers_common_sql-1.24.0-py3-none-any.whl.metadata (5.3 kB)
INFO: pip is still looking at multiple versions of apache-airflow-providers-common-sql to determine which version is compatible with other requirements. This could take a while.
  Using cached apache_airflow_providers_common_sql-1.23.0-py3-none-any.whl.metadata (5.2 kB)
  Using cached apache_airflow_providers_common_sql-1.21.0-py3-none-any.whl.metadata (6.2 kB)
  Using cached apache_airflow_providers_common_sql-1.20.0-py3-none-any.whl.metadata (6.2 kB)
  Using cached apache_airflow_providers_common_sql-1.19.0-py3-none-any.whl.metadata (6.2 kB)
  Using cached apache_airflow_providers_common_sql-1.18.0-py3-none-any.whl.metadata (6.2 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached apache_airflow_providers_common_sql-1.17.1-py3-none-any.whl.metadata (6.2 kB)
  Using cached apache_airflow_providers_common_sql-1.17.0-py3-none-any.whl.metadata (6.2 kB)
  Using cached apache_airflow_providers_common_sql-1.16.0-py3-none-any.whl.metadata (6.2 kB)
  Using cached apache_airflow_providers_common_sql-1.15.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: more-itertools>=9.0.0 in /home/loveadeola/anaconda3/lib/python3.13/site-packages (from apache-airflow-providers-common-sql->apache-airflow) (10.3.0)
Collecting sqlparse>=0.4.2 (from apache-airflow-providers-common-sql->apache-airflow)
  Using cached sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
INFO: pip is looking at multiple versions of apache-airflow-providers-ftp to determine which version is compatible with other requirements. This could take a while.
Collecting apache-airflow-providers-ftp (from apache-airflow)
  Using cached apache_airflow_providers_ftp-3.13.0-py3-none-any.whl.metadata (5.2 kB)
  Using cached apache_airflow_providers_ftp-3.12.3-py3-none-any.whl.metadata (5.2 kB)

In [4]:
from airflow import DAG
from airflow.providers.standard.operators.python import PythonOperator

In [6]:
import pandas as pd

[2025-07-30T01:33:52.675+0100] {utils.py:164} INFO - NumExpr defaulting to 4 threads.